---
apiVersion: v1
kind: "BuildConfig"
metadata:
  name: "cronjob-s2i-image-build"
  labels:
    app: cronjob-sample
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: "https://github.com/SagarOnline/openshift-samples-cronjob-java.git"
  strategy:
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "openjdk18-openshift:latest"
      incremental: true
  output:
    to:
      kind: "ImageStreamTag"
      name: "cronjob-sample:latest"

---
apiVersion: v1
kind: ImageStream
metadata:
  labels:
    app: cronjob-sample
  name: cronjob-sample
  
---
apiVersion: v1
data:
  password: MDViM2JiNGY3MTdiZTU3ZDRmZDdkMzNjMjE0MDgyMjY2YzgyOGFlNg==
  username: c2Nob3BhZGU=
kind: Secret
metadata:
  annotations:
    build.openshift.io/source-secret-match-uri-1: https://github.ibm.com/openshift-samples/*
  name: schopade-github-repo-access-secret
  labels:
    app: openshift-samples
type: kubernetes.io/basic-auth